variable "infra_env" {
  type = string
  description = "Infrastructre Environment"
}

variable "region" {
  default = "us-east-1"
  type = string
  description = "Infrastructure region"
}

variable "vpc_server_cidr" {
  type = string
  description = "IP range to use in server VPC"
  default = "10.0.0.0/16"
}

variable "vpc_database_cidr" {
  type = string
  description = "IP range to use for database VPC"
  default = "172.16.0.0/16"
}

variable "public_subnet_numbers" {
    type = map(number)
    description = "Map of az to a number that should be used for public subnet"

    default = {
      "us-east-1a" = 1
      "us-east-1b" = 2
      
    }
}

variable "private_subnet_numbers" {
  type = map(number)
  description = "Map of az to a number that should be used for public subnet"

  default = {
    "us-east-1a" = 3
    "us-east-1b" = 4
    
  }
}

variable "databaseInstanceVariable" {
  default = "db.t2.micro"
  description = "Database Instance Type"
  type = string
}

variable "peer_owner_id" {
  description = "The AWS account ID of the owner of the peer VPC"
  type = string
  
}

variable "peer_region" {
  default = "us-east-1"
  description = "Peering region"
  type = string
}

variable "loadblancer_certificate_arn" {
  description = "SSL certificate required"
  type = string
  
}

variable "database_username"{
  description = "Database username required"
  type = string
}

variable "database_password"{
  description = "Database password required"
  type = string
}

variable "database_name"{
  description = "Database name"
  type = string
}

variable "bastion_public_RSA_key"{
  description = "Public RSA key, which is generated by developer"
  type = string
}

variable "container_desired_count"{
  default = 1
  description = "No of container desired"
  type = number
}

variable "ecs_task_policy"{
  default = ["arn:aws:iam::aws:policy/SecretsManagerReadWrite", "arn:aws:iam::aws:policy/AmazonRDSDataFullAccess"]
  description = "List of policy that needs to be attached"
  type = list(string)
}